const mockWeatherData = {
  current: {
    location: "New York",
    country: "US",
    flag: "🇺🇸",
    temperature: 22,
    feelsLike: 25,
    condition: "Partly Cloudy",
    description: "Partly cloudy with gentle breeze",
    humidity: 65,
    windSpeed: 12,
    windDirection: "NW",
    pressure: 1013,
    visibility: 10,
    uvIndex: 6,
    sunrise: "06:24",
    sunset: "19:45",
    minTemp: 18,
    maxTemp: 26,
    icon: "partly-cloudy",
  },
  hourly: [
    {
      time: "12:00",
      temp: 22,
      icon: "partly-cloudy",
      condition: "Partly Cloudy",
    },
    { time: "13:00", temp: 24, icon: "sunny", condition: "Sunny" },
    { time: "14:00", temp: 26, icon: "sunny", condition: "Sunny" },
    { time: "15:00", temp: 25, icon: "cloudy", condition: "Cloudy" },
    { time: "16:00", temp: 23, icon: "rain", condition: "Light Rain" },
    { time: "17:00", temp: 21, icon: "rain", condition: "Rain" },
  ],
  weekly: [
    {
      day: "Today",
      minTemp: 18,
      maxTemp: 26,
      icon: "partly-cloudy",
      condition: "Partly Cloudy",
    },
    {
      day: "Tomorrow",
      minTemp: 20,
      maxTemp: 28,
      icon: "sunny",
      condition: "Sunny",
    },
    {
      day: "Wednesday",
      minTemp: 19,
      maxTemp: 25,
      icon: "rain",
      condition: "Rain",
    },
    {
      day: "Thursday",
      minTemp: 17,
      maxTemp: 23,
      icon: "cloudy",
      condition: "Cloudy",
    },
    {
      day: "Friday",
      minTemp: 21,
      maxTemp: 29,
      icon: "sunny",
      condition: "Sunny",
    },
    {
      day: "Saturday",
      minTemp: 22,
      maxTemp: 30,
      icon: "sunny",
      condition: "Sunny",
    },
    {
      day: "Sunday",
      minTemp: 20,
      maxTemp: 27,
      icon: "partly-cloudy",
      condition: "Partly Cloudy",
    },
  ],
};

export default mockWeatherData;
